### ISSUE TITLE
Adding widget src to the Web AppBuilder causes crash

### ISSUE THREAD

**Issue by SamDrummond** [WaimakaririGeospatial/LayerListWidget#1]
When using the Web AppBuilder developer edition locally, adding the src folder to the web appbuilder causes Node.js to crash. Preventing testing.

1. Rename the repo 'src' folder to 'LayerListWidget'
2. Run the WebAppBuilder using startup.bat
3. Paste the newly renames LayerListWidget folder to the [WAB]\client\stemapp\widgets - note that that original LayerList Widget is still in this directory and avaliable to the Web AppBuilder.
4. Node.js crashes and any changes to the Web AppBuilder Client result in an error message as follows:

![image](https://cloud.githubusercontent.com/assets/4656969/8710888/480f3470-2ba1-11e5-8b50-de56ff966522.png)

**Comment by arunsebastian** [comment]
Sam, Have you deleted the native  LayerList widget and replaced it with the new?

**Comment by arunsebastian** [comment]
The WAB frame expects the native LayerList to be rendered and loaded when an app is created.Hence  if it doesnt find it during the creation of the app,WAB crashes.The solution is to put LayerList and the new LayerListWidget in same widgets folder and then configure the native LayerList to be off and add the new widget instead.I hope this helps

**Comment by SamDrummond** [comment]
No I have not deleted the original layer list widget. I have simply added the new one to the  [WAB]\client\stemapp\widgets folder as LayerListWidget. 

Given that the source code is entirely different and the name is unique (LayerList vs LayerListWidget) - the Web AppBuilder should simply add it as another independent widget.

I'm a little confused when you say that the Web AppBuilder Framework is dependent on the LayerList widget. I can remove it from my app and remove it completely from the [WAB]\client\stemapp\widgets folder and the application will continue to work. So I do not believe that their are any dependancies between the Web AppBuilder and LayerList and LayerListWidget. 

You should be able recreate the error by following the workflow in the original post (which I have updated for clarity).

**Comment by arunsebastian** [comment]
I agree that there is no dependancy on LayerListWidget,but I have a strong reason to believe that there is a dependancy on the native  LayerList widget.I have came across this error once,when I actually removed the default LayerList  from the widgets folder and tried to create an app.Not sure about the exact work flow I followed then.
However,now that you havent deleted the native one,this may be something I need to  be looking into asap.

**Comment by SamDrummond** [comment]
Arun, here is the error message from Node.js

Read repository items: c:\arcgis\webappbuilder\client\stemapp\widgets
Server listening http connection on port 3345 in development mode
Server listening https connection on port 3346 in development mode
Possibly unhandled Error: Tried loading "c:\arcgis\webappbuilder\client\stemapp\widgets\LayerListWidget\nls\_widgetLabel\strings.js" at c:\arcgis\webappbuilder\client\stemapp\widgets\LayerListWidget\nls\_widgetLabel\strings.js then tried node's require("c:\arcgis\webappbuilder\client\stemapp\widgets\LayerListWidget\nls\_widgetLabel\strings.js") and it failed with error: Error: Cannot find module 'c:\arcgis\webappbuilder\client\stemapp\widgets\LayerListWidget\nls\_widgetLabel\strings.js'
    at c:\arcgis\webappbuilder\server\node_modules\requirejs\bin\r.js:2534:27
    at Object.context.execCb (c:\arcgis\webappbuilder\server\node_modules\requirejs\bin\r.js:1898:33)
    at Object.Module.check (c:\arcgis\webappbuilder\server\node_modules\requirejs\bin\r.js:1114:51)
    at Object.Module.enable (c:\arcgis\webappbuilder\server\node_modules\requirejs\bin\r.js:1391:22)
    at Object.context.enable (c:\arcgis\webappbuilder\server\node_modules\requirejs\bin\r.js:1759:39)
    at Function.req.get (c:\arcgis\webappbuilder\server\node_modules\requirejs\bin\r.js:2458:33)
    at Object.localRequire [as require] (c:\arcgis\webappbuilder\server\node_modules\requirejs\bin\r.js:1632:40)
    at requirejs (c:\arcgis\webappbuilder\server\node_modules\requirejs\bin\r.js:1985:24)
    at addI18NLabel (c:\arcgis\webappbuilder\server\rest\repo.js:1:6468)
    at getRepoItemFromFile (c:\arcgis\webappbuilder\server\rest\repo.js:1:5495)

Are their possibly files missing from the nls folder?

**Comment by Lizmgbs** [comment]
Can this now be close too?
