### ISSUE TITLE
Metadata Button Greyed Out

### ISSUE THREAD

**Issue by SamDrummond** [WaimakaririGeospatial/LayerListWidget#2]
The metadata icon is greyed out when a layer is out of scale range.

Workflow:

1. Open the layer list widget
2. Zoom to a scale where a layer is out of range and the label is greyed out
3. The metadata icon is also greyed out
4. Click on the metadata button
5. The metadata dialog opens

![image](https://cloud.githubusercontent.com/assets/4656969/8714887/7bb15ac4-2bce-11e5-91e5-b866074b831d.png)

I think it would be good for the user to be able access the metadata even when the layer is out of scale range - which is how it works. The issue is that the button appears greyed out and its not intuitive that the user can still click on the button

**Comment by arunsebastian** [comment]
Ready for testing

**Comment by Lizmgbs** [comment]
Part of latest update. Ready for testing
