### ISSUE TITLE
Layer Menu Transparency

### ISSUE THREAD

**Issue by SamDrummond** [WaimakaririGeospatial/LayerListWidget#3]
The layer menu is greyed out when a layer is out of scale range and displays behind the successive layer items.

1. Open the layer list widget
2. Zoom to a scale where a layer is out of range and the label is greyed out
3. Click on the layer menu
4. The menu opens but is displayed behind the the other layer items

![image](https://cloud.githubusercontent.com/assets/4656969/8714912/ced93974-2bce-11e5-9832-478b78cb39f6.png)

Neither the layer menu button nor the layer menu should be transparent and should display over the top of the other items.

**Comment by arunsebastian** [comment]
Read for  testing

**Comment by Lizmgbs** [comment]
Part of latest update today. Ready for testing
