### ISSUE TITLE
Dynamic Map Service Layers & Group layers not greyed out

### ISSUE THREAD

**Issue by SamDrummond** [WaimakaririGeospatial/LayerListWidget#4]
Dynamic Map Service layers (including group layers) not greyed out when they are out of range.

Workflow:

1. Open the layer widget
2. Zoom to a extent where a dynamic map service is not visible
3. Expand the map service to see the sub layers
4. The layer items appear as if they are visible when the are out of scale range

![image](https://cloud.githubusercontent.com/assets/4656969/8715009/cc36610a-2bcf-11e5-890f-5edb5c5d6fbc.png)

The issue is that users  will not know which layers are out of scale range.  If a dynamic map service or a group layer is out of scale range all child elements should display greyed out.

**Comment by Lizmgbs** [comment]
Ready for testing

**Comment by SamDrummond** [comment]
This is actually still occuring. Compare the layer list widget vs what the actual scale dependancies are in AGOL.

WAB:
![image](https://cloud.githubusercontent.com/assets/4656969/8972597/9f92c69e-36af-11e5-8e74-24d696a424f0.png)

AGOL:
![image](https://cloud.githubusercontent.com/assets/4656969/8972606/ae88c798-36af-11e5-993c-d97e49bbcb51.png)
