### ISSUE TITLE
Metadata Popup does not display as per requirement

### ISSUE THREAD

**Issue by SamDrummond** [WaimakaririGeospatial/LayerListWidget#5]
When the user clicks the metadata button ( i ) in the layer list the popup should be configured to display: 

Layer Alias: Web Map-> Layer Alias
Details: MXD->Feature Layer->Layer Properties->General Tab->Description
Credits: MXD->Feature Layer->Layer Properties->General Tab-> Credits
Use Limitation: ANZLIC Metadata->Item Description->Use Limitation
Date Last Updated:	ANZLIC Metadata->Citation->Dates->Revised

However, the metadata popup is currently displaying as follows:
Layer Alias: Web Map-> Layer Alias (correct)
Details: Nothing (error)
Credits: Nothing (error)
Use Limitation: ANZLIC Metadata->Item Description->Use Limitation (correct)
Date Last Updated:	ANZLIC Metadata->Item Description->Use Limitation (error)

Workflow (not avaliable on external site):

1. Open the layer list widget
2. Click on the layers metadata button
3. The following displays:

![image](https://cloud.githubusercontent.com/assets/4656969/8995720/5ab52676-3767-11e5-8fb9-fc5cece9d014.png)

**Comment by arunsebastian** [comment]
Sam,Can you provide us with a  sample json response for the request or expose a rest end point so that we can access?

**Comment by SamDrummond** [comment]
@arunsebastian - our ArcGIS Server is currently down - so I can't sorry. Will send you it through when I get access again. Until then I will leave this assigned to me.

**Comment by SamDrummond** [comment]
This is looking better but we still do not have the credits showing up:

![image](https://cloud.githubusercontent.com/assets/4656969/9050316/a7d2bfea-3aa0-11e5-9e4b-da5f52e81456.png)

This is configured in ArcMap to display as follows:

![image](https://cloud.githubusercontent.com/assets/4656969/9050322/bd88f804-3aa0-11e5-91b8-4d109fa221dc.png)

**Comment by SamDrummond** [comment]
Also, can the date please be formatted to something sensible - so dd-mm-yyyy and remove the time.

**Comment by arunsebastian** [comment]
Sam..can you send us the getMetadata response having Credits in it.Will format the updated field in the mean time

**Comment by SamDrummond** [comment]
We might need to chat about this - as I'm not sure the server object extension can be configured to return those parameters. Unless you know of a way to do it.
